import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import RootLayout from '@/components/Layouts/RootLayout'
import { Button, Col, Row } from 'antd'
import ItemCard from '@/components/Reusable/ItemCard'

const inter = Inter({ subsets: ['latin'] })

export default function HomePage({products}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: '20px' }}>
      <Row gutter={[16, 16]}>
        {
        products?.map((product, index) => (
          <Col key={index} xs={24} sm={12} md={8} lg={6}>
          {/* <p>{product.lenght}</p> */}
            <ItemCard product ={product} />
          </Col>
        ))
        }
      </Row>
    </div>
    </>
  )
}

HomePage.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};

export const getServerSideProps = async()=>{
  const res = await fetch('http://localhost:3000/api/product')
  const data = await res.json()
  return{
    props: {
      products: data.data
    }
  }
}
