import RootLayout from "@/components/Layouts/RootLayout";
import SelectProduct from "@/components/Reusable/SelectProduct";
import { Col, Row } from "antd";
import Head from "next/head";

export default function SelectItem({categories}) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
     
      
        <Row gutter={[16, 16]}>
          {
          categories?.map((category, index) => (
            <Col key={index} xs={24} sm={12} md={8} lg={6}>
            {/* <p>{product.lenght}</p> */}
           <SelectProduct category ={category} />
            </Col>
          ))
          }
        </Row>
      </>
    
    )
  }

  SelectItem.getLayout = function getLayout(page) {
    return <RootLayout>{page}</RootLayout>;
  };
  
  export const getServerSideProps = async (context) => {
      const { params } = context
      const res = await fetch(`${process.env.BASE_URL}/selectItem/${params?.id}`)
      const data = await res.json()
    
  
      return { props: { categories: data.data } }
  }